apps/cliente/urls.py
from django.conf.urls import url, include
from apps.cliente.views import cliente


urlpatterns = [
    url(r'^$', cliente,name='cliente'),
]

apps/home/urls.py
from django.conf.urls import url, include
from apps.home.views import home

urlpatterns = [
    url(r'^$', home,name='home'),
]

apps/limpieza/urls.py
from django.conf.urls import url, include
from apps.limpieza.views import limpieza

urlpatterns = [
    url(r'^$', limpieza,name='limpieza'),
]

apps/login/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

urlpatterns= [
	
	url(r'^accounts/login/', login, {'template_name':'index.html'}, name= 'login')
	#url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login')
]

apps/preguntas/urls.py
from django.conf.urls import url, include
from apps.preguntas.views import preguntas

urlpatterns = [
    url(r'^$', preguntas,name='preguntas'),
]

apps/servicios/urls.py
from django.conf.urls import url, include
from apps.servicios.views import servicios

urlpatterns = [
    url(r'^$', servicios,name='servicios'),
]

apps/usuario/urls.py
from django.conf.urls import url
from apps.usuario.views import RegistroUsuario



urlpatterns= [
	url(r'^resgistro',RegistroUsuario.as_view(), name="registrar")


]

emprendimiento/urls.py
from django.conf import settings
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm,password_reset_complete
from apps.trabaja import views as trabaj_views
from apps.contacto import views  as contact_views
from apps.contratar import views as contrata_views




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('apps.home.urls',namespace='home')),
    url(r'^usuario/', include('apps.usuario.urls',namespace='usuario')),
    url(r'^limpieza/', include('apps.limpieza.urls',namespace='limpieza')),
    url(r'^login/', include('apps.login.urls',namespace= 'login')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name= 'login'),
    url(r'^servicios/', include('apps.servicios.urls',namespace='servicios')),
    url(r'^preguntas/', include('apps.preguntas.urls',namespace='preguntas')),
    url(r'^cliente/', include('apps.cliente.urls',namespace='cliente')),
    url(r'^trabaja/$', trabaj_views.trabaja, name='trabaja'),
    url(r'^contratar/$', contrata_views.contratar, name='contratar'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^contacto/', contact_views.contacto, name='contacto'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),

    ]

apps/cliente/models.py
from django.db import models

# Create your models here.

apps/home/models.py
from django.db import models

# Create your models here.

apps/login/models.py
from django.db import models

# Create your models here.

apps/contacto/forms.py
from django import forms


class contactForm(forms.Form):
	nombre= forms.CharField(required =False, max_length=100,  widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su nombre'}))
	email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su correo'}))
	mensaje = forms.CharField(required=True,max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su mensaje'}))

apps/trabaja/forms.py
from django import forms


class trabajtForm(forms.Form):
	nombre= forms.CharField(required =False, max_length=100,  widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su nombre'}))
	apellido=forms.CharField(required =False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su apeliido'}))
	telefono=forms.CharField(required =False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su telefono'}))
	cedula=forms.CharField(required =False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su cedula'}))
	email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese su correo'}))
	ciudad = forms.CharField(required=True,max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese la ciudad donde vive'}))

apps/usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from django.core.validators import EmailValidator
from django import forms


class RegistroForm(UserCreationForm):

	class Meta:
		model=User
		fields=[
		  'username',
		  'first_name',
		  'last_name',
		  'email',


		 
		]

		labels={
		  'username': 'Nombre de usuario',
		  'first_name': 'Nombre',
		  'last_name': 'Apellidos',
		  'email': 'Correo',
		  
		}
	   
	

apps/cliente/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def cliente(request):
	return render(request,'cliente/cliente.html')

apps/contacto/views.py
from django.shortcuts import render

from django.core.mail import send_mail
from django.conf import settings

from .forms import contactForm

def contacto(request):
	title='Contacto'
	form = contactForm(request.POST or None)
	context = {'title': title, 'form':form, }
	

	if form.is_valid():
		name = form.cleaned_data['nombre']
		name1 = form.cleaned_data['email']
		comment = form.cleaned_data['mensaje']
		print ( form.cleaned_data['email'])
		subject = 'Mensaje'
		message = '%s %s %s ' %(name,comment,name1)
		emailFrom = form.cleaned_data['email']
		emailTo = [settings.EMAIL_HOST_USER]
		send_mail(subject, message, emailFrom, emailTo, fail_silently=True)	

	template = 'contacto/contacto.html'
	return render(request,template,context)

apps/home/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def home(request):
	return render(request,'home/home.html')

apps/limpieza/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def limpieza(request):
	return render(request,'limpieza/limpieza.html')

apps/login/views.py
from django.shortcuts import render

# Create your views here.

apps/trabaja/views.py
from django.shortcuts import render

from django.core.mail import send_mail
from django.conf import settings

from .forms import trabajtForm

def trabaja(request):
	title='¿Quieres trabajar con nosotros? envianos tus datos.'
	form = trabajtForm(request.POST or None)
	context = {'title': title, 'form':form, }
	

	if form.is_valid():
		name = form.cleaned_data['nombre']
		name1=form.cleaned_data['apellido']
		name2=form.cleaned_data['telefono']
		name3=form.cleaned_data['cedula']
		comment = form.cleaned_data['ciudad']
		print ( form.cleaned_data['email'])
		subject = 'Mensaje de Usuario'
		message = '%s %s %s %s %s' %(name,name1,name2,name3,comment)
		emailFrom = form.cleaned_data['email']
		emailTo = [settings.EMAIL_HOST_USER]
		send_mail(subject, message, emailFrom, emailTo, fail_silently=True)	
		title="Gracias !"
		confirm_message ="El mensaje ha sido enviado, una persona de nuestro equipo te llamará en menos de 48 horas"
		context = {'title': title, 'confirm_message':confirm_message, }

	template = 'trabaja/trabaja.html'
	return render(request,template,context)

apps/usuario/views.py
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy
from apps.usuario.forms import RegistroForm
from django.shortcuts import render, redirect

# Create your views here.

class RegistroUsuario(CreateView):	
	model=User
	template_name="usuario/registro.html"
	form_class=RegistroForm
	
	success_url=reverse_lazy('home:home')

templates/base/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
	<title>DomestiCasa</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

	<!-- !Contenido de la pagina! -->

<div class="w3-top">
  <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
    <a href="\home" class="w3-button">DomestiCasa</a>
    <!-- Right-sided naclass="w3-bar-itemvbar links. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="#about" class="w3-bar-item w3-button">About</a>
      <a href="\servicios" class="w3-bar-item w3-button">Nuestros servicios</a>
      <a href="{% url 'trabaja' %}" class="w3-bar-item w3-button">¿Buscas trabajo?</a>
      <a href="{% url 'contacto' %}" class="w3-bar-item w3-button">Contacto</a>
      <a href=" {% url 'login:login' %}"  class="w3-bar-item w3-button">Ingresar</a>
      <a href="{% url 'usuario:registrar' %}" class="w3-bar-item w3-button">Registrase</a>
    </div>
  </div>
</div>

{% block nav %}

{% endblock %}
{% block content %}
<h4>bloque de contenido </h4>
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

templates/base/base1.html
{% load staticfiles %}
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
	<title>DomestiCasa</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

	<!-- !Contenido de la pagina! -->



{% block nav %}

{% endblock %}
{% block content %}
<h4>bloque de contenido </h4>
{% endblock %}

{% block footer %}
{% endblock %}
</body>
</html>

templates/base/base22.html
{% extends 'base/base1.html' %}
{% load staticfiles %}
{% block content%}
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
<body class="w3-light-grey ">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-container"><br>
         <h2>DomestiCasa</h2> <br>
         <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i><a href="\cliente" >Inicio</p>
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i><a href="\limpieza" >Limpieza</p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i>Promociones</p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>compras</p>
          <a href="{% url 'logout' %}" class="w3-bar-item w3-button w3-teal "></i>Salir</a><br>

         
          <br>
        </div>
      </div><br>
    <div>
  <div>
<div>

  </body>
  </html>
  {% endblock%}

templates/index.html
{% extends 'base/base.html' %}

{% block title %}
{% endblock %}
{% block navbar%}
{% endblock %}
{% block content %}

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="w3-container w3-half  " style="margin-top: 120px">
<form method="post">
	{% csrf_token %}
	   <div class="row">
        <div class="col-md-8 col-md-offset-8">
        		<label for="username">Nombre de usuario:</label>
        	<p><input class="w3-input w3-border" type="text" placeholder="Nombre" requiered name="username">
              </p>
        </div>
           </div>
        <div class="row">
        <div class="col-md-8 col-md-offset-8">
        		<label for="username">Contraseña:</label>
        		<p><input class="w3-input w3-border" type="password" placeholder="Contraseña" required name="password">
                </p>
       </div>
           </div>
    <div class="row">
    	<div class="col-md-8 col-md-offset-8">
    		<div class="form-group">
                <a href="{% url 'password_reset' %}" >Olvidé mi contraseña</a>
        		<input class="btn btn-primary" type="submit" value="Ingresar">
    	   </div>
        </div>
    </div>
</form>


{% endblock %}